fix: SQLite3 gem dependency issue
From Travis:
LoadError: Error loading the 'sqlite3' Active Record adapter. Missing a
gem it depends on? can't activate sqlite3 (~> 1.3.6), already activated
sqlite3-1.4.0. Make sure all dependencies are added to Gemfile.

To fix, locked SQLite3 to 1.4.x